#!/bin/bash

cp "/usr/portage/${1}-9999.ebuild" "/usr/portage/${1}-9999.ebuild.damn"

"./damnation/${1}-9999.ebuild.patcher"
emerge -av ${1}

cp "/usr/portage/${1}-9999.ebuild.damn" "/usr/portage/${1}-9999.ebuild"
